name: finger_signer
description: finger-signing demonstration
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0 <4.0.0"
flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
