name: finger_signer
author: allen brunson
description: finger-signing demonstration
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"
flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
